# Generated by Django 4.2.4 on 2023-11-19 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('identification_type', models.CharField(max_length=255)),
                ('identification_number', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image', models.URLField(max_length=2048)),
                ('release_date', models.DateField()),
                ('protagonist', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('productor', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('popularity', models.FloatField()),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('rental_date', models.DateTimeField()),
                ('rental_deadline', models.DateTimeField()),
                ('price', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('games', models.ManyToManyField(to='api.game')),
            ],
        ),
    ]
